version: '3'

services:
  localsite-ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      # Choose the default provider (azure_openai or gemini)
      - DEFAULT_PROVIDER=azure_openai
    # volumes:
    #   - ./:/app
    extra_hosts:
      # Important: Allows access to the host machine
      - "host.docker.internal:host-gateway"